repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^addons/
      - id: end-of-file-fixer
        exclude: ^addons/
      - id: check-yaml
        exclude: ^addons/
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        exclude: ^addons/

  - repo: local
    hooks:
      - id: gdformat
        name: Auto-format GDScript (gdformat)
        entry: gdformat
        language: system
        files: \.gd$
        exclude: ^addons/
        pass_filenames: true

      - id: gdlint
        name: Lint GDScript (gdlint)
        entry: gdlint
        language: system
        files: \.gd$
        exclude: ^addons/
        pass_filenames: true
