# "Binding (8), set (0) was not provided."
# Let's look at `SunshineCloudsPostCompute.comp`. We removed `scene_data_block` which was binding 8.
# BUT wait! Does Godot cache compute shaders? YES! If the SPIRV is cached, the Godot Engine will throw this error because the GDScript is creating the uniform set WITHOUT binding 8, but the shader might still be compiling with binding 8!
# BUT wait, this is a python script (`submit`) that failed? No, `submit` failed because the PRECOMMIT hook or TESTS ran and failed.
# Wait, let's check `tests/` or anything that failed. The `submit` error is generated by Godot running.
# Let's delete `.godot/shader_cache` if it exists.
rm -rf .godot/shader_cache
