echo "Wait, Postpass has 8 uniform variables."
echo "0: input_data_image"
echo "1: input_color_image"
echo "2: reflections_sample"
echo "3: input_screen_image"
echo "4: output_screen_image"
echo "5: depth_image"
echo "6: genericData"
echo "7: LightsBuffer"
echo "Ah, it was missing binding 8 in Postpass before I touched it? No, binding 8 was scene_data_block! We removed binding 8!"
