#define SCENE_DATA_FLAGS_USE_AMBIENT_LIGHT (1 << 0)
#define SCENE_DATA_FLAGS_USE_AMBIENT_CUBEMAP (1 << 1)
#define SCENE_DATA_FLAGS_USE_REFLECTION_CUBEMAP (1 << 2)
#define SCENE_DATA_FLAGS_USE_ROUGHNESS_LIMITER (1 << 3)
#define SCENE_DATA_FLAGS_USE_FOG (1 << 4)
#define SCENE_DATA_FLAGS_USE_UV2_MATERIAL (1 << 5)
#define SCENE_DATA_FLAGS_USE_PANCAKE_SHADOWS (1 << 6)
#define SCENE_DATA_FLAGS_IN_SHADOW_PASS (1 << 7)
#define MAX_VIEWS 2

#define GODOT_VERSION_MAJOR 4
#define GODOT_VERSION_MINOR 7

#ifndef MSAA_ENABLED
	#define MSAA_ENABLED 0
#endif

#if (!MSAA_ENABLED)
	#define Sampler2DMSAA                              sampler2D
	#define Image2DMSAA                                image2D
	#define textureSizeMSAA(sampler_)                  textureSize(sampler_, 0)
	#define textureSamplesMSAA(sampler_)               (1)
	#define texelFetchMSAA(sampler_, P_, sample_)      texelFetch(sampler_, P_, 0)
	#define imageStoreMSAA(image_, P_, sample_, data_) imageStore(image_, P_, data_)
#else
	#define Sampler2DMSAA                              sampler2DMS
	#define Image2DMSAA                                image2DMS
	#define textureSizeMSAA(sampler_)                  textureSize(sampler_)
	#define textureSamplesMSAA(sampler_)               textureSamples(sampler_)
	#define texelFetchMSAA(sampler_, P_, sample_)      texelFetch(sampler_, P_, sample_)
	#define imageStoreMSAA(image_, P_, sample_, data_) imageStore(image_, P_, sample_, data_)
#endif // !MSAA_ENABLED



struct GenericData{
	vec3 extralargenoiseposition;
	float extralargenoisescale;

	vec3 largenoiseposition;
	float cloud_lighting_sharpness;

	vec3 mediumnoiseposition;
	float lighting_step_distance;

	vec3 smallnoiseposition;
	float atmospheric_density;

	vec4 ambientLightColor;
	vec4 ambientGroundLightColor;
	vec4 ambientfogdistancecolor;
	
	float small_noise_scale;
	float min_step_distance;
	float max_step_distance;
	float lod_bias;

	float cloud_sharpness;
	float directionalLightsCount;
	float powderStrength;
	float anisotropy;

	float cloud_floor;
	float cloud_ceiling;
	float max_step_count;
	float max_lighting_step_count;

	float atmosphere_simple_blend;
	float blurPower;
	float blurQuality;
	float curlPower;

	vec2 WindDirection;
	float fogEffectGround;
	float samplePointsCount;

	float pointLightsCount;
	float pointEffectorCount;
	float windSweptRange;
	float windSweptPower;
    
    vec2 raster_size;
	float large_noise_scale;
	float medium_noise_scale;

	float time;
	float cloud_coverage;
	float cloud_density;
	float small_noise_strength;

	float cloud_lighting_power;
	float accumilation_decay;
	float isAccumulationA;
    float resolutionscale;
    float z_far;
    vec3 pad;

    mat4 cam_projection;
    mat4 cam_inv_projection;
    mat4 cam_view;
    mat4 cam_inv_view;

    mat4 prev_cam_projection;
    mat4 prev_cam_inv_projection;
    mat4 prev_cam_view;
    mat4 prev_cam_inv_view;
};

struct DirectionalLight {
	vec4 direction; //w = shadow sample count
	vec4 color; //a = intensity
};

struct PointLight {
	vec4 position; //w = radius
	vec4 color; //a = intensity
};

struct PointEffector {
	vec3 position; //w = radius
	float radius;

	float power;
	float attenuation;
	vec2 reserved;
};
