@tool
class_name PhysicsCable3D
extends Node3D

@export_category("Cable Connections")
@export var start_anchor: Node3D
@export var end_plug: RigidBody3D

@export_category("Physics Properties")
@export var link_scene: PackedScene = preload("res://interactables/cable_link.tscn")
@export var cable_length_meters: float = 3.0
@export var link_spacing: float = 0.2

@export_category("Appearance")
@export var cable_color: Color = Color(0.1, 0.1, 0.1)
@export var thickness: float = 0.04

@export_category("Debug")
@export var show_debug_sphere: bool = true:
	set(value):
		show_debug_sphere = value
		if is_instance_valid(_debug_sphere):
			_debug_sphere.visible = show_debug_sphere
			print("PhysicsCable3D: show_debug_sphere toggled to ", show_debug_sphere)

# Grab the internal node directly. Ensure the name exactly matches your node!
@onready var _editor_icon: Node3D = get_node_or_null("%EditorIcon")

static var _material_cache: Dictionary = {}

var _links: Array[RigidBody3D] = []
var _visual_segments: Array[MeshInstance3D] = []
var _base_mesh: CylinderMesh
var _debug_sphere: MeshInstance3D


func _ready() -> void:
	if not Engine.is_editor_hint():
		# 1. Purge the editor icon immediately at runtime
		if is_instance_valid(_editor_icon):
			_editor_icon.queue_free()

		_create_base_mesh()
		
		# 2. ONLY generate physics and visuals if we are actually playing the game
		call_deferred("_generate_physics_chain")
		call_deferred("_generate_visual_segments")
	else:
		# 3. ONLY generate the debug sphere in the editor
		_setup_debug_sphere()


func _create_base_mesh() -> void:
	_base_mesh = CylinderMesh.new()
	_base_mesh.top_radius = thickness
	_base_mesh.bottom_radius = thickness
	_base_mesh.height = 1.0
	_base_mesh.radial_segments = 8
	_base_mesh.rings = 1

	if not _material_cache.has(cable_color):
		var mat := StandardMaterial3D.new()
		mat.albedo_color = cable_color
		mat.roughness = 0.8
		_material_cache[cable_color] = mat
		
	_base_mesh.material = _material_cache[cable_color]


func _setup_debug_sphere() -> void:
	print("PhysicsCable3D: _setup_debug_sphere() cleaning up old debug nodes and generating new one.")
	
	# Clean up ghost nodes generated by previous @tool script reloads
	for child in get_children():
		if child.name == "DebugSphereMesh":
			child.queue_free()
	
	_debug_sphere = MeshInstance3D.new()
	_debug_sphere.name = "DebugSphereMesh" # Name it so we can easily find and destroy it later
	
	var sphere_mesh := SphereMesh.new()
	var mat := StandardMaterial3D.new()
	
	# Create a soft, unshaded transparent material for the editor
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	mat.albedo_color = Color(1.0, 0.7, 0.0, 0.15)
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	
	sphere_mesh.material = mat
	_debug_sphere.mesh = sphere_mesh
	_debug_sphere.top_level = true
	_debug_sphere.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	_debug_sphere.visible = show_debug_sphere
	
	add_child(_debug_sphere)


func _process(_delta: float) -> void:
	if Engine.is_editor_hint():
		_update_debug_sphere_transform()
		return

	if _links.is_empty() or _visual_segments.is_empty():
		return

	if not is_instance_valid(start_anchor) or not is_instance_valid(end_plug):
		return

	# 1. Gather all current global positions in order
	var points: Array[Vector3] = []
	points.append(start_anchor.global_position)
	
	for link in _links:
		if is_instance_valid(link):
			points.append(link.global_position)
			
	points.append(end_plug.global_position)

	# 2. Stretch and aim the cylinders between every point
	for i in range(points.size() - 1):
		var p1 := points[i]
		var p2 := points[i + 1]
		var dist := p1.distance_to(p2)

		var segment := _visual_segments[i]
		segment.global_position = p1.lerp(p2, 0.5) 

		var dir := p2 - p1
		if dir.length() > 0.001:
			var up := Vector3.UP if abs(dir.normalized().y) < 0.99 else Vector3.RIGHT
			segment.look_at(p2, up)
			segment.rotate_object_local(Vector3.RIGHT, PI / 2.0)

		segment.scale = Vector3(1.0, dist, 1.0)


func _update_debug_sphere_transform() -> void:
	if show_debug_sphere and is_instance_valid(_debug_sphere) and is_instance_valid(start_anchor):
		_debug_sphere.global_position = start_anchor.global_position
		
		# Cable length is the radius, so the scale multiplier is length * 2
		var diameter := cable_length_meters * 2.0
		_debug_sphere.scale = Vector3(diameter, diameter, diameter)


func _generate_visual_segments() -> void:
	# Create one mesh segment for every gap between links
	var total_points: int = _links.size() + 1
	
	for i in range(total_points):
		var segment := MeshInstance3D.new()
		segment.mesh = _base_mesh
		segment.top_level = true
		add_child(segment)
		_visual_segments.append(segment)


func _generate_physics_chain() -> void:
	print("PhysicsCable3D: _generate_physics_chain() generating bi-directional cable.")
	
	if not link_scene:
		printerr("CABLE ERROR: You forgot to assign the link_scene in the inspector!")
		return

	if not is_instance_valid(start_anchor) or not is_instance_valid(end_plug):
		return

	var total_links: int = int(cable_length_meters / link_spacing)

	# --- Link both plugs together bi-directionally! ---
	if end_plug.get_class() == "TetheredPlug" or end_plug.has_method("get_class"): 
		if "max_cable_length" in end_plug:
			end_plug.max_cable_length = cable_length_meters
		if "anchor_point" in end_plug:
			end_plug.anchor_point = start_anchor
		if "partner_plug" in end_plug and "partner_plug" in start_anchor:
			end_plug.partner_plug = start_anchor

	if start_anchor.get_class() == "TetheredPlug" or start_anchor.has_method("get_class"):
		if "max_cable_length" in start_anchor:
			start_anchor.max_cable_length = cable_length_meters
		if "anchor_point" in start_anchor:
			start_anchor.anchor_point = end_plug
		if "partner_plug" in start_anchor:
			start_anchor.partner_plug = end_plug
	# -------------------------------------------------------

	var start_pos := start_anchor.global_position
	var end_pos := end_plug.global_position
	var previous_body: Node3D = start_anchor

	var straight_dist := start_pos.distance_to(end_pos)
	var droop_amount: float = maxf(0.0, cable_length_meters - straight_dist) * 0.5

	for i in range(total_links):
		var link := link_scene.instantiate() as RigidBody3D
		
		# Force cable links to be incredibly light so they don't drag the held plug
		link.mass = 0.05 
		add_child(link)

		for prev in _links:
			link.add_collision_exception_with(prev)
			
		if start_anchor is PhysicsBody3D:
			link.add_collision_exception_with(start_anchor)

		var fraction := float(i + 1) / float(total_links + 1)
		var drop_offset: Vector3 = Vector3.DOWN * (4.0 * droop_amount * fraction * (1.0 - fraction))
		link.global_position = start_pos.lerp(end_pos, fraction) + drop_offset

		if not link.global_position.is_equal_approx(previous_body.global_position):
			link.look_at(previous_body.global_position)

		_links.append(link)

		var joint := PinJoint3D.new()
		add_child(joint)
		joint.global_position = previous_body.global_position.lerp(link.global_position, 0.5)

		if previous_body is PhysicsBody3D:
			joint.node_a = joint.get_path_to(previous_body)

		joint.node_b = joint.get_path_to(link)
		previous_body = link

	var final_joint := PinJoint3D.new()
	add_child(final_joint)
	final_joint.global_position = previous_body.global_position.lerp(end_pos, 0.5)
	final_joint.node_a = final_joint.get_path_to(previous_body)
	final_joint.node_b = final_joint.get_path_to(end_plug)

	if end_plug is CollisionObject3D:
		for prev in _links:
			end_plug.add_collision_exception_with(prev)
